version: "3.8"
services:
  db:
    container_name: db
    restart: always
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    expose:
      - 5432
  web:
    container_name: web
    restart: always
    image: web:latest
    build:
      context: .
      dockerfile: deploy/Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PRODUCTION=True
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - TZ=Asia/Tashkent
volumes:
  pgdata:
