# Generated by Django 4.0.4 on 2022-05-24 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='cats/%Y/%m/%d', verbose_name='Изображение')),
                ('age', models.DateField(verbose_name='Возраст')),
                ('desc', models.CharField(max_length=255, verbose_name='Описание')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.breed', verbose_name='Парода')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
